# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_sup": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://alibabz.github.io/nbdev_testing/"

git_url = "https://github.com/alibabz/nbdev_testing/tree/master/"

def custom_doc_links(name): return None
